name: test
on:
  push:
    branches:
      - master
  schedule:
    - cron: '0 1 * * *'

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: archlinux
      options: --privileged
      volumes:
        - /sys/fs/cgroup:/sys/fs/cgroup
    steps:
      - uses: actions/checkout@v2
      - name: Update system and install dependencies
        run: pacman -Syu --noconfirm --noprogressbar --needed base-devel devtools btrfs-progs dbus sudo
      - name: Populate /etc/machine-id
        run: dbus-uuidgen --ensure=/etc/machine-id
      - name: Setup mkepkg configuration
        run: sed -i -e "s|MAKEFLAGS=.*|MAKEFLAGS=-j$(nproc)|"
                    -e "s|#PKGDEST=.*|PKGDEST='$HOME/packages'|"
                    -e "s|#SRCDEST=.*|SRCDEST='$HOME/sources'|"
                    -e "s|#SRCPKGDEST=.*|SRCPKGDEST='$HOME/srcpackages'|"
                    -e "s|#LOGDEST=.*|LOGDEST='$HOME/makepkglogs'|"
                    /etc/makepkg.conf
      - name: Setup build user
        run: |
          useradd -m user
          chown -R user "$HOME" "$GITHUB_WORKSPACE"
      - name: Build yosys-git
        run: |
          cd "$GITHUB_WORKSPACE"/yosys-git
          extra-x86_64-build -- -U user

